### ISSUE TITLE
Allow defining the `destination` field in configuration

### ISSUE THREAD

**Issue by amitds1997** [IamTheFij/release-gitter#4]
I am trying to use this package to provide GitHub release pre-commit hook for [selene](https://github.com/Kampfkarren/selene/pull/565) just like StyLua. 

The problem: `selene` release packages the binary `selene` and that conflicts with the top level folder `selene` in the repo. So, the error is:
```python
IsADirectoryError: [Errno 21] Is a directory: '<local-path>/selene/selene'
```

This does not happen when using the CLI command because it allows specifying destination.

**Reproduction steps**
1. Clone [amitds1997/selene](https://github.com/amitds1997/selene)
2. Run `pip wheel .` directly or in a virtualenv

**Possible resolution**
1. Allow passing `destination` in pyproject configuration ([source](https://github.com/IamTheFij/release-gitter/blob/ddf509e9a435e0a351a6d7a031daadc3ef58da47/pseudo_builder.py#L24)).
2. Pass `destination` to [`download_asset`](https://github.com/IamTheFij/release-gitter/blob/ddf509e9a435e0a351a6d7a031daadc3ef58da47/pseudo_builder.py#L54) call.

**Comment by IamTheFij** [comment]
Sorry, I totally lost track of this and noticed it when looking at selene myself! Rather than making the download destination configurable, I'm instead using the build directory. That should achieve the same goal of avoiding conflicting file names.
